server:
  port: '8080'

spring:
  datasource:
    username: sa
    url: jdbc:h2:file:C:/Users/pragrawal/Downloads/customer-service/customer-service/src/main/resources/db2/db2
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

cipher:
  secure-key: 'MySuperSecretKey'
  name: 'AES/CBC/PKCS5Padding'
  algo: 'AES'

